version: "3"
 
services:   
  servicio_php-apache-xdebug:
    container_name: php-apache-mysql-XDebug7  # toasterlint/php-apache-mysql
    build: .
    volumes:
      # Montamos a web desde fóra no directorio web do contenedor
      - ./php/src:/var/www/html
      - ./xdebug:/var/logs/xdebug
    ports:
      - 8000:80

  db:
   container_name: db7
   image: mysql
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: proba
    MYSQL_USER: usuario
    MYSQL_PASSWORD: abc123.
   volumes:
    - ./dbdata:/var/lib/mysql
   ports:
     - 9906:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin7
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    
    

